/**
 * create-issues.ts — Creates Forgejo/GitHub issues from USER_STORIES.md
 * Parses dependencies "**Dépend de :** US-001, US-002" and registers them
 * in the orchestrator via POST /deps for the DAG.
 *
 * Required env:
 *   REPO              owner/repo
 *   GIT_PROVIDER_1_URL
 *   GIT_PROVIDER_1_TOKEN (or FORGEJO_TOKEN)
 *   AGENT_GIT_LOGIN   (default: agent)
 *   STORIES_FILE      (default: docs/spec/USER_STORIES.md)
 *   ORCHESTRATOR_URL  (default: http://localhost:9001)
 */

import { readFileSync, existsSync } from 'node:fs';
import { request as httpRequest } from 'node:http';
import { request as httpsRequest } from 'node:https';
import { loadProviders, getProviderForRepo } from '../../git-provider/index.js';

interface Story {
  usId: string;
  usNum: string;
  fullTitle: string;
  body: string;
  deps: string[];
}

interface ApiResult {
  status: number;
  data: Record<string, unknown>;
}

const REPO = process.env.REPO ?? '';
const AGENT_LOGIN = process.env.AGENT_GIT_LOGIN ?? 'agent';
const STORIES_FILE = process.env.STORIES_FILE ?? 'docs/spec/USER_STORIES.md';
const ORCHESTRATOR_URL = process.env.ORCHESTRATOR_URL ?? 'http://localhost:9001';

if (!REPO) { console.error('REPO not defined'); process.exit(1); }

let provider: ReturnType<typeof getProviderForRepo>;
try {
  const gitProviders = loadProviders();
  provider = getProviderForRepo(REPO, gitProviders);
  if (!provider) throw new Error(`No provider found for ${REPO}`);
} catch (e) {
  console.error(`Git provider error: ${(e as Error).message}`);
  process.exit(1);
}

if (!existsSync(STORIES_FILE)) {
  console.error(`USER_STORIES.md not found: ${STORIES_FILE}`);
  process.exit(1);
}

const content = readFileSync(STORIES_FILE, 'utf8');

// ── Parse USER_STORIES.md ───────────────────────────────────────────────────

const stories: Story[] = [];
const sections = content.split(/(?=^## US-)/m).filter(s => s.trim());

for (const section of sections) {
  const lines = section.split('\n');
  const headerLine = lines[0]!.trim();

  const headerMatch = headerLine.match(/^## (US-(\d+)[^#\n]*)/);
  if (!headerMatch) continue;

  const fullTitle = headerMatch[1]!.trim();
  const usNum = headerMatch[2]!;
  const usId = `US-${usNum}`;

  const bodyLines = lines.slice(1);
  const deps: string[] = [];
  const depsLineIdx = bodyLines.findIndex(l =>
    /^\*\*[Dd]épend de\s*:\*\*/.test(l.trim()),
  );

  if (depsLineIdx >= 0) {
    const depsMatch = bodyLines[depsLineIdx]!.match(/\*\*[Dd]épend de\s*:\*\*\s*(.+)/);
    if (depsMatch) {
      const rawDeps = depsMatch[1]!.split(',').map(s => s.trim());
      for (const d of rawDeps) {
        const dm = d.match(/US-(\d+)/);
        if (dm) deps.push(dm[1]!);
      }
    }
  }

  const body = bodyLines.join('\n').trim();
  stories.push({ usId, usNum, fullTitle, body, deps });
}

if (!stories.length) {
  console.log('No user story found. Expected format: ## US-001 — Title');
  process.exit(0);
}

// ── API calls ───────────────────────────────────────────────────────────────

const [owner, repoName] = REPO.split('/');

const apiRequest = (method: string, urlStr: string, payload?: object): Promise<ApiResult> =>
  new Promise((resolve, reject) => {
    const u = new URL(urlStr);
    const body = payload ? JSON.stringify(payload) : null;
    const reqLib = u.protocol === 'https:' ? httpsRequest : httpRequest;
    const opts = {
      method,
      hostname: u.hostname,
      port: u.port || (u.protocol === 'https:' ? 443 : 80),
      path: u.pathname + u.search,
      headers: {
        'Content-Type': 'application/json',
        ...(body ? { 'Content-Length': Buffer.byteLength(body).toString() } : {}),
      },
    };
    const req = reqLib(opts, res => {
      let d = '';
      res.on('data', (c: string) => d += c);
      res.on('end', () => {
        try { resolve({ status: res.statusCode!, data: JSON.parse(d) as Record<string, unknown> }); }
        catch { resolve({ status: res.statusCode!, data: { raw: d } }); }
      });
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });

const createIssue = async (story: Story) => {
  const bodyText = story.body +
    (story.deps.length
      ? `\n\n---\n**Depends on:** ${story.deps.map(n => `#${n}`).join(', ')}`
      : '') +
    '\n\n*Automatically generated by `/spec init`*';

  return provider!.provider._req('POST', `/repos/${owner}/${repoName}/issues`,
    { title: story.fullTitle, body: bodyText, assignees: [AGENT_LOGIN] });
};

// ── Load specialist triggers from rules.yaml for auto-tagging ───────────────

const loadTriggers = (): Record<string, string[]> => {
  const rulesPath = (process.env.RULES_FILE ?? `${process.env.WORKSPACE ?? '.'} /.coderclaw/rules.yaml`).trim();
  try {
    if (!existsSync(rulesPath)) return {};
    const rulesContent = readFileSync(rulesPath, 'utf8');
    const triggers: Record<string, string[]> = {};
    const specSection = rulesContent.split(/^specialists:\s*$/m)[1] ?? '';
    const blocks = specSection.split(/\n  (\w+):\s*\n/);
    for (let i = 1; i < blocks.length; i += 2) {
      const name = blocks[i]!;
      const block = blocks[i + 1] ?? '';
      const m = block.match(/triggers:\s*\[([^\]]+)\]/);
      if (m) {
        triggers[name] = m[1]!.split(',').map(t => t.trim().replace(/['"]/g, '').toLowerCase());
      }
    }
    return triggers;
  } catch { return {}; }
};

const detectGates = (storyText: string, triggers: Record<string, string[]>): string[] => {
  const text = storyText.toLowerCase();
  const gates: string[] = [];
  for (const [role, keywords] of Object.entries(triggers)) {
    for (const kw of keywords) {
      if (text.includes(kw)) { gates.push(role); break; }
    }
  }
  return gates;
};

const SPECIALIST_TRIGGERS = loadTriggers();

// ── Main ────────────────────────────────────────────────────────────────────

const main = async () => {
  console.log(`\n=== /spec init — ${stories.length} user stories on ${REPO} ===\n`);

  const usToIssueNum: Record<string, number> = {};

  for (const story of stories) {
    try {
      const r = await createIssue(story);
      const data = r.data as Record<string, unknown>;
      if (data?.number) {
        usToIssueNum[story.usNum] = data.number as number;

        const gates = detectGates(`${story.fullTitle} ${story.body}`, SPECIALIST_TRIGGERS);
        for (const gate of gates) {
          await provider!.provider.setLabel(`${owner}/${repoName}`, data.number as number, `gate:${gate}`).catch(() => {});
        }

        const gateStr = gates.length ? ` [${gates.map(g => `gate:${g}`).join(', ')}]` : '';
        console.log(`#${data.number} ${story.fullTitle}${gateStr}` +
          (story.deps.length ? ` [depends on: ${story.deps.map(n => `US-${n}`).join(', ')}]` : ''));
      } else {
        console.error(`${story.fullTitle} : ${JSON.stringify(data).slice(0, 100)}`);
      }
      await new Promise(r => setTimeout(r, 600));
    } catch (e) {
      console.error(`${story.fullTitle} : ${(e as Error).message}`);
    }
  }

  const hasDeps = stories.filter(s => s.deps.length > 0);
  if (hasDeps.length > 0) {
    console.log(`\n=== Registering ${hasDeps.length} dependencies in the orchestrator ===`);
    for (const story of hasDeps) {
      const issueNum = usToIssueNum[story.usNum];
      if (!issueNum) continue;

      const depIssueNums = story.deps
        .map(usNum => usToIssueNum[usNum])
        .filter((n): n is number => n !== undefined);

      if (depIssueNums.length === 0) continue;

      try {
        await apiRequest('POST', `${ORCHESTRATOR_URL}/deps`,
          { repo: REPO, issueId: issueNum, deps: depIssueNums.map(String) });
        console.log(`#${issueNum} waits for [${depIssueNums.map(n => `#${n}`).join(', ')}]`);
      } catch (e) {
        console.error(`Deps #${issueNum}: ${(e as Error).message} (non-blocking)`);
      }
    }
  }

  console.log('\nDone.');
  if (Object.keys(usToIssueNum).length > 0) {
    const ready = stories.filter(s => s.deps.length === 0);
    console.log(`   ${ready.length} issue(s) ready to start immediately.`);
    console.log(`   ${hasDeps.length} issue(s) waiting on dependencies.`);
    console.log('   The RBAC pipeline starts automatically via Forgejo webhook.');
  }
};

main().catch(e => {
  console.error(`Fatal: ${(e as Error).message}`);
  process.exit(1);
});
